version: "2"
services:
  sfmrabbit:
      image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
      environment:
          - TZ=America/New_York
          - RABBITMQ_DEFAULT_USER=sfm_user
          - RABBITMQ_DEFAULT_PASS=password
  sfmtwitterrestharvester:
#      image: gwul/sfm-twitter-rest-harvester:master
      image: docker_sfmtwitterrestharvester
      links:
          - sfmrabbit:mq
      volumes:
          - "..:/opt/sfm-twitter-harvester"
      environment:
          - TZ=America/New_York
          - TWITTER_CONSUMER_KEY
          - TWITTER_CONSUMER_SECRET
          - TWITTER_ACCESS_TOKEN
          - TWITTER_ACCESS_TOKEN_SECRET
          - DEBUG=true
          - RABBITMQ_USER=sfm_user
          - RABBITMQ_PASSWORD=password
  sfmtwitterstreamharvester:
#      image: gwul/sfm-twitter-stream-harvester:master
      image: docker_sfmtwitterstreamharvester
      links:
          - sfmrabbit:mq
      volumes:
          - "..:/opt/sfm-twitter-harvester"
      environment:
          - TZ=America/New_York
          - TWITTER_CONSUMER_KEY
          - TWITTER_CONSUMER_SECRET
          - TWITTER_ACCESS_TOKEN
          - TWITTER_ACCESS_TOKEN_SECRET
          - DEBUG=true
          - RABBITMQ_USER=sfm_user
          - RABBITMQ_PASSWORD=password
