sfmrabbit:
    image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
    #RabbitMQ 3-management
    environment:
        - TZ=America/New_York
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-twitter-harvester"
    environment:
        - TZ=America/New_York
        - TWITTER_CONSUMER_KEY
        - TWITTER_CONSUMER_SECRET
        - TWITTER_ACCESS_TOKEN
        - TWITTER_ACCESS_TOKEN_SECRET
    command: bash -c "pip install -r requirements/master.txt --upgrade && appdeps.py --port-wait mq:5672 && python twitter_harvester.py --debug=True service mq sfm_user password"
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-twitter-harvester"
    environment:
        - TZ=America/New_York
        - TWITTER_CONSUMER_KEY
        - TWITTER_CONSUMER_SECRET
        - TWITTER_ACCESS_TOKEN
        - TWITTER_ACCESS_TOKEN_SECRET
    command: bash -c "pip install -r requirements/master.txt --upgrade && appdeps.py --port-wait mq:5672 && supervisord -c /etc/supervisor/supervisord.conf && stream_consumer.py mq sfm_user password twitter_harvester harvest.start.twitter.twitter_filter,harvest.start.twitter.twitter_sample /opt/sfm-twitter-harvester/twitter_harvester.py --debug=True"
