sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-twitter-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
    environment:
        - DEBUG=True
#    restart: always
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-twitter-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
#    restart: always
    environment:
        - DEBUG=True
