sfmrabbit:
    image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
    #RabbitMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=America/New_York
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
